# Configuration for Alacritty, the GPU enhanced terminal emulator.
window:
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 0
    y: 0

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  decorations: buttonless

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: SimpleFullscreen


  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.8

# Font configuration (changes require restart)
font:
  normal:
    # Font family: JetBrainsMono NF / FiraCode Nerd Font
    family: "JetBrainsMono NF"

  # Point size
  size: 17.5

colors:
  cursor:
    text: '#fefff2'
    cursor: '#f0cc09'

  selection:
    text: '#b5b5b5'
    background: '#18354f'

  primary:
    background: '#132738'
    foreground: '#ffffff'

  normal:
    black: '#000000'
    red: '#ff0000'
    green: '#38de21'
    yellow: '#ffe50a'
    blue: '#1460d2'
    magenta: '#ff005d'
    cyan: '#00bbbb'
    white: '#bbbbbb'

  bright:
    black: '#555555'
    red: '#f40e17'
    green: '#3bd01d'
    yellow: '#edc809'
    blue: '#5555ff'
    magenta: '#ff55ff'
    cyan: '#6ae3fa'
    white: '#ffffff'
theme: Cobalt-2

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

