# Make sure to clone the themes first, refer https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"

[font]
size = 19
# Other good fonts: JetBrainsMono Nerd Font, MonaspiceAr Nerd Font
normal.family = "GeistMono Nerd Font"
# italic.family = "MonaspiceAr Nerd Font"
# bold.family = "JetBrainsMono Nerd Font"
# bold_italic.family = "MonaspiceRn Nerd Font"

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[window]
decorations = "Buttonless"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.95
startup_mode = "Maximized"
blur = true

[window.padding]
x = 6
y = 6

[mouse]
hide_when_typing = true
